### ISSUE TITLE
Character Sheet wont open after migrating to 13

### ISSUE THREAD

**Issue by tasandberg** [NecroticGnome/ose-foundry-core#95]
### What happened?

I have an existing world that I built out in v12. Gave v13 a shot and ran into the following error. This error doesn't happen in a fresh world, only in my world I migrated from v12.

1. Updated foundry to v13 from v12
2. Performed data migration on world as per the dialog that pops up when launching it for the first time in v13.
3. World loaded
4. Clicking on any actor in the right-hand toolbar does nothing and shows this error in console:

```
hook.js:608 Error: An error occurred while rendering H 83. Cannot read properties of undefined (reading 'sort')
[Detected 1 package: system:ose(2.1.1)]
    at Hooks.onError (foundry.mjs:23747:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.mjs:37128:15Caused by: TypeError: Cannot read properties of undefined (reading 'sort')
[Detected 1 package: system:ose(2.1.1)]
    at character-sheet.js:235:7
    at Array.forEach (<anonymous>)
    at H._prepareItems (character-sheet.js:234:10)
    at H.getData (character-sheet.js:243:49)
    at H._render (foundry.mjs:37171:29)
    at H._render (foundry.mjs:37938:17)
    at H._render (foundry.mjs:38534:17)
    at H.render (foundry.mjs:37126:10)
    at ActorDirectory._onClickEntry (foundry.mjs:107077:20)
    at #onClickEntry (foundry.mjs:107051:17)
    at #onClickAction (foundry.mjs:28048:56)
    at #onClick (foundry.mjs:28001:51)
```

### What is the expected behaviour?

When I click the actor, the character sheet should show up.

### Relevant Errors and Warnings

```shell
hook.js:608 Error: An error occurred while rendering H 83. Cannot read properties of undefined (reading 'sort')
[Detected 1 package: system:ose(2.1.1)]
    at Hooks.onError (foundry.mjs:23747:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.mjs:37128:15Caused by: TypeError: Cannot read properties of undefined (reading 'sort')
[Detected 1 package: system:ose(2.1.1)]
    at character-sheet.js:235:7
    at Array.forEach (<anonymous>)
    at H._prepareItems (character-sheet.js:234:10)
    at H.getData (character-sheet.js:243:49)
    at H._render (foundry.mjs:37171:29)
    at H._render (foundry.mjs:37938:17)
    at H._render (foundry.mjs:38534:17)
    at H.render (foundry.mjs:37126:10)
    at ActorDirectory._onClickEntry (foundry.mjs:107077:20)
    at #onClickEntry (foundry.mjs:107051:17)
    at #onClickAction (foundry.mjs:28048:56)
    at #onClick (foundry.mjs:28001:51)
```

### Additional Support Details

Foundry Virtual Tabletop: Version 13 Stable, 13.346
Game System: ose, 2.1.1
Active Modules: 23

Performance Mode: Medium
Screen Dimensions: 2560 × 1440
Viewport Dimensions: 2844 × 1438

OS: macOS 15.5.0 arm (64-bit)
Client: Not)A;Brand/8.0.0.0
GPU: ANGLE (Apple, ANGLE Metal Renderer: Apple M2, Unspecified Version)
Max Texture Size: 16384

No viewed scene
Actors: 418 | Items: 804 | Journal Entries: 81 | Rollable Tables: 42 |
Playlists: 5 | Compendium Packs: 58 | Chat Messages: 0

World Scripts: None

### Foundry VTT Core Version

Foundry Virtual Tabletop: Version 13 Stable, 13.346

### Old-School Essentials Core Version

2.1.1

**Comment by tasandberg** [comment]
Yo, I tried doing a hard-refresh on the browser and it fixed itself. Thanks!

**Comment by sneat** [comment]
Good to hear it's solved @tasandberg
